name: Git Version

on:
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - name: tag-version
          # You may pin to the exact commit or the version.
          # uses: juliansangillo/tag-version@0ca10cb901a4e3273715c4443e5dec5ad8f40328
        uses: juliansangillo/tag-version@v1.5
        with:
            # The branch to use for stable releases in production. Default is master
          production-branch: main
            # The branch to use for dev deployments. Default is develop
          dev-branch: dev


